---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test-api-roald"
  namespace: "infra"
  labels:
    app: "test-api-roald"
    component: "cool-component"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "test-api-roald"
      component: "cool-component"
  strategy:
    rollingUpdate:
      maxSurge: 150%
      maxUnavailable: 60%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: "test-api-roald"
        component: "cool-component"
    spec:
      nodeSelector:
        node-pool-group: standard
      tolerations:
        - key: node-pool-group
          operator: Equal
          value: standard
          effect: NoSchedule
      containers:
        - name: fun-api
          image: eu.gcr.io/nube-hub/roald-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 350m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            timeoutSeconds: 1
            successThreshold: 1
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "test-api-roald-service"
  namespace: "infra"
  labels:
    app: "test-api-roald"
    component: "cool-component"
spec:
  ports:
    - name: metrics
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: "test-api-roald"
    component: "cool-component"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-api-roald-monitor
  namespace: "infra"
  labels:
    app: "test-api-roald"
    component: "cool-component"
spec:
  selector:
    matchLabels:
      app: "test-api-roald"
      component: "cool-component"
  endpoints:
  - port: metrics
    honorLabels: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: "test-api-roald"
    component: "cool-component"
  name: test-api-roald-policy
  namespace: infra
spec:
  ingress:
  - ports:
    - port: 8000
      protocol: TCP
  podSelector:
    matchLabels:
      app: "test-api-roald"
      component: "cool-component"
  policyTypes:
  - Ingress
